### PR TITLE
Stacked Denoising Autoencoder

### PR DESCRIPTION
**Pull request by vanshsoni**
Hey @the-ethan-hunt, Check notebook for stacked denoising autoencoder and give feedback

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
@vanshsoni , great examples! But can you tweak the parameters or reduce the coefficient a little bit more to improve the accuracy? Can this be possible?

**Comment by vanshsoni** [comment]
This can be possible but the learner can do that by reducing coefficient from 0.3 to other.
I stated in notebook also about coefficient 
Right now I used 0.3 as a coefficient.

**Comment by the-ethan-hunt** [comment]
Yes, that's what I meant. Can you calculate the coefficient for the maximum accuracy and implement it? I already have given a hint

**Comment by vanshsoni** [comment]
I change coefficient from 0.3 to 0.1 and 0.2 but the most accurate comes with 0.3 as a noise coefficient

**Comment by the-ethan-hunt** [comment]
That's what I was asking you. :smiley:

**Pull request merged**
