### PR TITLE
List frameworks and libraries in readme

### PR DESCRIPTION
**Pull request by MVenkata-Rathnam**
Solves #3 Issue

### CODE REVIEW

**Comment by dhruvapte26** [comment]
@MVenkata-Rathnam any specific reason for switching to Python 2.7?

**Comment by MVenkata-Rathnam** [comment]
**@the-ethan-hunt**  I have no specific reason.  My default python version is 2.7.  Since I was going to edit only the readme file I didn't change it.  I also think you haven't mentioned any specific python version to be used anywhere in the repo.

**Comment by dhruvapte26** [comment]
@MVenkata-Rathnam no need to do that. Please revert back to Python 3 and we are then good to merge.

**Comment by MVenkata-Rathnam** [comment]
Okay

**Pull request closed without merging**
