### PR TITLE
LSTM using Tensorflow

### PR DESCRIPTION
**Pull request by vanshsoni**
Hey @the-ethan-hunt I have added LSTM sentiment analysis notebook using tensorflow and with data set (data.zip)
Reference - Udacity Deep Learning Course

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
The `notebook` has no outputs in it. Just the inputs. We want the outputs too!

**Comment by vanshsoni** [comment]
ok sure i am adding resulted notebook

**Comment by vanshsoni** [comment]
@the-ethan-hunt Please now check it
I have added resultant file

**Comment by the-ethan-hunt** [comment]
Looks great to me. Merging it. :tada:

**Pull request merged**
