### PR TITLE
Multi layer perceptron using tensorflow

### PR DESCRIPTION
**Pull request by vanshsoni**

### CODE REVIEW

**Comment by vanshsoni** [comment]
@the-ethan-hunt are you going to review so thatIi can make other PR
thank you

**Comment by the-ethan-hunt** [comment]
@vanshsoni , I hope you are also understanding the code you write and not just copying code from some other repo and getting a PR here. There is no explanation of the code, just the titles.

**Comment by vanshsoni** [comment]
@the-ethan-hunt I am learning machine learning through this event that why I am making the notebooks and understanding each concept. Even I have created recurrent network

**Comment by the-ethan-hunt** [comment]
Alright @vanshsoni , but please add the information and not just the code

**Comment by the-ethan-hunt** [comment]
@vanshsoni , are you working on this? :smile:

**Comment by vanshsoni** [comment]
Yes, I am working.
I will make updates soon.

**Comment by the-ethan-hunt** [comment]
Pinging @vanshsoni ! Are you working on this?

**Comment by vanshsoni** [comment]
Hey I have added some details to files please do check and give feedback on that 
I have also created recurrent network model

**Comment by the-ethan-hunt** [comment]
Great going! 
P.S. Submit the RNN under a new PR

**Pull request merged**
