### PR TITLE
AutoEncoders using tensorflow and MNIST Data Sets

### PR DESCRIPTION
**Pull request by vanshsoni**
Please Review it

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
It would be great if you also provide the explanations on its working @vanshsoni

**Comment by vanshsoni** [comment]
sure i will provide details about that but please assign this to me
thanks

**Comment by vanshsoni** [comment]
Please check now I have added relevant comments and details

**Comment by the-ethan-hunt** [comment]
Great! Merging the PR. :tada:

**Pull request merged**
